### ISSUE TITLE
[debug]"add debug configuration" gives wrong suggestion in the first time

### ISSUE THREAD

**Issue by kpge** [eclipse-theia/theia#5804]
### Description
the first time click 'Add Configuration' gives the wrong suggestion regardless the `launch.json` file is existed.
![image](https://user-images.githubusercontent.com/35068357/61923162-8fdb1b80-af95-11e9-8c2b-1d3b2eafcc02.png)

### Reproduction Steps
* close the `launch.json` file 
* refresh the browser
* click `Add Configuration` in the debug widget

**OS and Theia version:**
theia:5c298024b5f5d705e6a53eaeb4660083350be91b
**Diagnostics:**

**Comment by akosyakov** [comment]
in the example app? or you install some vscode extensions?

**Comment by kpge** [comment]
> in the example app? or you install some vscode extensions?

I start theia in example app

**Comment by kpge** [comment]
It looks like that json language server had not been ready when the command `editor.action.triggerSuggest` is executed

**Comment by akosyakov** [comment]
@kpge Do you want to investigate?

**Comment by kpge** [comment]
> @kpge Do you want to investigate?

@akosyakov I don't find where the json language server start, is it it monaco editor core?

**Comment by akosyakov** [comment]
It should be started whenever a workspace has json file: https://github.com/theia-ide/theia/blob/2befdf4cbebbbddb9719e0b88a578fba13f61808/packages/json/src/browser/json-client-contribution.ts#L82-L87

Maybe it just takes time or there is a bug and globs are never match.

**Comment by kpge** [comment]
> It should be started whenever a workspace has json file:
> 
> https://github.com/theia-ide/theia/blob/2befdf4cbebbbddb9719e0b88a578fba13f61808/packages/json/src/browser/json-client-contribution.ts#L82-L87
> 
> Maybe it just takes time or there is a bug and globs are never match.

It won't be called until a json file is opened, I think there's a bug here.

**Comment by akosyakov** [comment]
> It won't be called until a json file is opened, I think there's a bug here.

It should be fine, some language servers are started only when file is opened. 

I've noticed that you don't have syntax coloring. It means that is not an issues with a language server, but a language itself. An editor is opened before the language is registered and auto detects a language as plain text.

We fixed something like that for the plugin system: https://github.com/theia-ide/theia/pull/5754 I think we need to generalize it for textmate grammar contributions.

**Comment by kpge** [comment]
The `registerTextmateLanguage` will be called when the workspace is loaded, and when the  json file is colored, it still shows the wrong suggestion.
![image](https://user-images.githubusercontent.com/35068357/62001090-9a72ed80-b11a-11e9-9a13-e16837ad7d20.png)

**Comment by akosyakov** [comment]
@kpge Could you try with https://github.com/theia-ide/theia/pull/6145 please?

**Comment by kpge** [comment]
> @kpge Could you try with #6145 please?

no，It still gives the same wrong suggestion.

**Comment by vince-fugnitto** [comment]
@kpge I've tried recently and it works correctly for me, can you confirm?

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/68145305-830a8400-ff03-11e9-974e-f19a37f6f151.png)

</div>

**Comment by kpge** [comment]
@vince-fugnitto No, it still gives the wrong suggestion. Are you cloesed all the json file and refresh the page?
![image](https://user-images.githubusercontent.com/35068357/68924639-3ef96800-07bc-11ea-828d-ce8c1559d4d8.png)

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto No, it still gives the wrong suggestion. Are you cloesed all the json file and refresh the page?
> ![image](https://user-images.githubusercontent.com/35068357/68924639-3ef96800-07bc-11ea-828d-ce8c1559d4d8.png)

Sorry for the late reply, I must have missed the notification.
I have retried recently and still cannot reproduce the issue. If you still experience the issue can you please provide the list of steps to reproduce and list of extensions included?

**Comment by kpge** [comment]
@vince-fugnitto sorry for the late reply too
I pulled the code and checked this issue, and found that this bug had been fixed!

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto sorry for the late reply too
> I pulled the code and checked this issue, and found that this bug had been fixed!

Great, and no worries! :smiley:
