### ISSUE TITLE
VSCode extension with HTML part broken

### ISSUE THREAD

**Issue by lemmy** [eclipse-theia/theia#6578]
### Description
The [TLA+ VSCode extension](https://github.com/alygin/vscode-tlaplus/releases/tag/v1.2.0) has rendering issues with Theia and Theia fails completely with the extension's HTML part.

Gitpod with hash ```f5d7d65f-bdab-4f57-994b-3ad1539792bb``` was created from this [TLA+ spec](https://github.com/lemmy/BlockingQueue).

### Reproduction Steps
![Peek 2019-11-18 21-10](https://user-images.githubusercontent.com/88777/69118797-85afc200-0a49-11ea-8744-4df6fb5afc1b.gif)

### In VSCode
![Peek 2019-11-18 21-15](https://user-images.githubusercontent.com/88777/69118887-c576a980-0a49-11ea-95ee-5dab831330e4.gif)

/cc @alygin

**Comment by akosyakov** [comment]
Assume that it should be fixed by https://github.com/eclipse-theia/theia/pull/6465 Could you try please?

**Comment by akosyakov** [comment]
with #6465:
<img width="1552" alt="Screen Shot 2019-11-19 at 09 17 31" src="https://user-images.githubusercontent.com/3082655/69128864-72ced900-0aad-11ea-9a8f-6ebf0831b724.png">

It does not look good because the extension is not designed to work remotely. It uses vscode-resource scheme csp sources: https://github.com/alygin/vscode-tlaplus/blob/f1fb18ef796181f42ab74b3fc53b2d976ba9edec/resources/check-result-view.html#L5

It's obviously does not work when resources are served from the http endpoint. It has to be fixed to use `webview.cspSource` as described in VS Code docs: https://code.visualstudio.com/api/extension-guides/webview#content-security-policy

**Comment by alygin** [comment]
@akosyakov, thanks for the clarification. You're right, the TLA+ extension still uses the old (pre-1.38) WebView API and has rather strict security policies. Here's the issue about upgrading: https://github.com/alygin/vscode-tlaplus/issues/111

Switching to the new API is an easy task, but unfortunately it still doesn't make the extension work in Theia. It looks like Theia doesn't provide this new API and throws the "viewPanel.webview.asWebviewUri is not a function" error. Any plans on supporting it?

There's another option -- working with the old API in the extension, but ease the security policies. It might help with loading the resources, but I would keep it as a last resort.

**Comment by akosyakov** [comment]
> Switching to the new API is an easy task, but unfortunately it still doesn't make the extension work in Theia. It looks like Theia doesn't provide this new API and throws the "viewPanel.webview.asWebviewUri is not a function" error. Any plans on supporting it?

@alygin not on master, PR to properly support WebViews is here: https://github.com/eclipse-theia/theia/pull/6465

**Comment by alygin** [comment]
Sure, here it is: 
[vscode-tlaplus-1.2.1.vsix.zip](https://github.com/eclipse-theia/theia/files/3868553/vscode-tlaplus-1.2.1.vsix.zip)

**Comment by akosyakov** [comment]
@alygin I've tried, it does not work for me, looking at the code, this part looks suspicious:
```ts
const resourcesDiskPath = vscode.Uri.file(path.join(extContext.extensionPath, 'resources'));
    const resourcesPath = viewPanel.webview.asWebviewUri(resourcesDiskPath);
    if (!viewHtml) {
        viewHtml = fs.readFileSync(path.join(resourcesPath.fsPath, 'check-result-view.html'), 'utf8');
    }
    
```

`asWebviewUri` returns an external URI to load local content, in remote content it is something like `http://webview-host/vscode-resource/file/...`. The point is that you cannot read filesystem with that and you should not. The extension is always running on the workspace machine and you can just do `fs.readFileSync(path.join(path.join(extContext.extensionPath, 'resources', 'check-result-view.html')), 'utf8');`.

Important that within the webview resources should be loaded using links created by `asWebviewUri`.

**Comment by akosyakov** [comment]
And if i replace reading html file from the disk, it works 🎉 
<img width="1552" alt="Screen Shot 2019-11-20 at 11 40 40" src="https://user-images.githubusercontent.com/3082655/69232093-adf30a00-0b8a-11ea-9473-badf8b9517cc.png">

**Comment by alygin** [comment]
> ...The point is that you cannot read filesystem with that and you should not...

Yeah, I didn't notice that. Thanks!

**Comment by alygin** [comment]
@akosyakov, there's one problem left -- source file links are not displayed in the result view. Could you, please, click the "Full output" link and send me the contents of the output channel that will open? I'll try to figure out how to fix those links.

**Comment by alygin** [comment]
@akosyakov, sorry, never mind, I managed to obtain it myself with the old extension version.

**Comment by alygin** [comment]
@akosyakov, it looks like the problem is with css-styles. For instance, there's the table named Coverage on the panel. The Action column of this table contains links ("Init" and "Next" are links), yet they are displayed as simple text. Could you, please, check them? Is it really a style-related problem?

**Comment by akosyakov** [comment]
@alygin I will check it tomorrow!

**Comment by alygin** [comment]
@akosyakov, please, also have a look at those "M" symbols to the right of some of the error trace tree items. They have a [css-style](https://github.com/alygin/vscode-tlaplus/blob/45846bedf5dca23526b6b3e5d89427efc94cc1a1/resources/check-result-view.css#L169) with the color `var(--vscode-gitDecoration-modifiedResourceForeground)` (should be blue in the default color scheme), yet it's displayed as a simple text.

There're other similar css-styles that don't work. The mentioned variables come from the [Theme Color reference](https://code.visualstudio.com/api/references/theme-color).

**Comment by akosyakov** [comment]
@alygin missing `var(--vscode-gitDecoration-modifiedResourceForeground)` is expected, Theia does not come with built-in VS Code extension by default, and this color is contributed by git vscode extension. It should work with https://github.com/eclipse-theia/theia/pull/6475 though given that the give vscode extension is installed.

Anyway, thank you for spotting it!

**Comment by alygin** [comment]
Got it, thanks!

Then the only problem left is with link styles. It's strange that some links are displayed correctly ("Full output", "Hide/Show unmodified" ), and others aren't.

The only difference I see is that those links that are displayed correctly, have the "title" attribute.

**Comment by akosyakov** [comment]
@alygin I've inspected these elements and they don't look like `a` tags, they are `td` elements:
<img width="1336" alt="Screen Shot 2019-11-21 at 14 33 07" src="https://user-images.githubusercontent.com/3082655/69342482-f46c6580-0c6b-11ea-912f-1b382cb340f7.png">

I'm not sure that it is Theia issue. We don't mutate HTML content, except rewriting old `vscode-resource` URLs to external URLs.

**Comment by akosyakov** [comment]
While debugging something strange happening here:
<img width="1336" alt="Screen Shot 2019-11-21 at 14 40 11" src="https://user-images.githubusercontent.com/3082655/69342957-e4a15100-0c6c-11ea-9878-3d52b0a1af86.png">

`item.range` is an object, but treated as an array

**Comment by alygin** [comment]
@akosyakov, you've spotted it correctly, `appendCodeLinkChild()` won't add the `<a>` element if the last parameter is empty.

I guess, this issue can be closed. All the problems are either fixed or covered in other specialised issues. @lemmy?

**Comment by lemmy** [comment]
I don't know how to test the changes and thus are not qualified to comment.

**Comment by akosyakov** [comment]
I will close the issue as soon as we merge https://github.com/eclipse-theia/theia/pull/6465 It won't be available in Gitpod immediately, some integration work is required, but hopefully soon.

**Comment by akosyakov** [comment]
General support in Theia resolved by https://github.com/eclipse-theia/theia/pull/6465
