### ISSUE TITLE
[vscode] support viewsWelcome contribution point

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7178]
There is a new contribution point which allow to control welcome view for contributed views: https://github.com/microsoft/vscode/blob/cce81b98b9507b9f4baee1fcf4c9972e88d65a48/src/vs/workbench/contrib/welcome/common/viewsWelcomeExtensionPoint.ts

It's already used by latest version of vscode built-in git extension: https://github.com/microsoft/vscode/issues/61491#issuecomment-586945696

**Comment by alex-gilin** [comment]
We've introduced viewsWelcome contributed point in some custom extensions... Can you prioritize this task?

**Comment by akosyakov** [comment]
@alex-gilin There is not really "you"? There are different adopters contributing to this project. For now i am not sure there anyone has capacity for it. I've added to next dev meeting to raise it, but one should point out some interesting VS Code extensions to justify it for concrete adopter. PRs are also welcomed. Usually one study VS Code implementation for a reference and then port it to Theia trying not break APIs outside of the plugin system.

**Comment by akosyakov** [comment]
Supporting this would be interesting for better initial git and debug views.

**Comment by amiramw** [comment]
@esterw1109 will try to work on it

**Comment by clovis-dugue** [comment]
Hi ; has this issue been fixed ? I can see the PR has been merged and the [changelog](https://raw.githubusercontent.com/theia-ide/theia/master/CHANGELOG.md) mentions it, however my custom extension's `viewWelcome` does not show.  

Maybe opening a new issue for this would be relevant but I would rather note duplicate this one

**Comment by EstherPerelman** [comment]
@clovis-dugue The issue has been fixed, What is your code for viewsWelcome? Are you sure it has to work?

**Comment by clovis-dugue** [comment]
@EstherPerelman Thanks for the lightning fast answer.  
My code is as simple as :
```json
"viewsWelcome": [
			{
				"view": "mission-panel",
				"contents": "[Show mission](command:side-mission-panel.show-mission)\n[End mission](command:side-mission-panel.end-mission)\n[Cancel mission](command:side-mission-panel.cancel-mission)\n"
			}
		]
```
Inside the `package.json`.  

It does work as intended when packaged as a `vsix` and used inside of VSCode, but not when when packaged as a `.theia`. I am testing the `vsix` inside of Theia right now

**Comment by EstherPerelman** [comment]
@clovis-dugue It's very strange, Has to work as explained in **How to test** PR #8678

**Comment by clovis-dugue** [comment]
It does indeed ; the main difference between these two plugins being that mine fails to activate (for testing purposes).  
However when failing to activate inside VSCode, it still shows the ViewsWelcome. In Theia, this does not seem to be the case ; which might be an oversight in the API implementation.

**Comment by EstherPerelman** [comment]
> @EstherPerelman It does indeed ; the main difference between these two plugins being that mine fails to activate (for testing purposes).
> However when failing to activate inside VSCode, it still shows the ViewsWelcome. In Theia, this does not seem to be the case ; which might be an oversight in the API implementation.

You should really open a new issue for that case..

**Comment by clovis-dugue** [comment]
Further investigation shows that a "Hello World" plug-in straight from VSCode's generator will have the same issue ; the example provided in the PR still works. I'm opening a new issue.

**Comment by davide-sergi** [comment]
You need to register a `TreeDataProvider` which return an empty tree. This is not required for vscode environment.
You can keep same `package.json`.

I solved with following code:
```

import * as vscode from 'vscode';

export async function activate(context: vscode.ExtensionContext) { 
  vscode.window.registerTreeDataProvider(
	  "my-view-id",
	  new EmptyTreeDataProvider()
  );
}

export function deactivate() {}

export class EmptyTreeDataProvider implements vscode.TreeDataProvider<any> {
	constructor() {}

	getTreeItem(element: any): vscode.TreeItem {
		return {};
	}

	getChildren(element?: any): Thenable<any[]> {
		return new Promise((resolve) => resolve([]));
	}
}



```

**Comment by tsmaeder** [comment]
The contribution point has been implemented, but there remains an issue: https://github.com/eclipse-theia/theia/issues/9361
